language: node_js
node_js:
- '6'
- '7'
- '8'
deploy:
  provider: npm
  email: billing.relate@schibsted.media
  on:
    branch: master
    node: '8'
  api_key:
    secure: B5v003qKYOgoyZXUlKyEZ9g2i+gRzt+HjDwVbnAZB+A1LGhBCVGdf18J0qnGBYH2WtJfVCES4VpzlvL5tbxPhShZ80frhkg9BOSshq6TQD8XxCeH9DqH9tqrY/ItY3z6EmUIgAuqR2yJer56Ayoy7slpDVikYtlinGAGxtWGRfXOHj9zNS7PXlQQ4xm9Ufd9BoBY+pRDS+zVv9QfD/ETA3V1BeGHcCpsPnBqQQ5VKt6crP0Y+mWf3lET3RWb+vRt5vTamT6vfLz6HcTrLhR9x+HI+pGtAoIs1xiy+JzFpSpAIOSxsJMj1TAYo4vNqdzQDWx96Y+zwiTysr6Wj68pvxN0oRpU/+Nymil9ZjXCyMycNQv7dL3rdwsAtc1WXbS1Ov2yUHBMWzc8IIpWdXs9ThMIudeN70VY//1UD0Sq3iS9zbSBswubcUozGfBahEQBo4H9OP1XC4Zz59tNvbKRsxVXKfzQB+Gavz5poKP8Bj/rwoJKWzwj2mU4wrmtf6tX1Rf565D8zobRPyBxbTSsKgIeyRDoluePvN1HBLw9Vu7W6O1hxnikWZKhEyLMlXgtz18lWhAI1K8Q92ztEPfSg+/51PS5e+31x44q6PlmpvkzuNmKIQFdIaIJzOCWXZ/NZHPSLZ7L+Bo9D1Hj+KU2nLXvQvxq03IJzk+jv9d+Bx8=
